-- Add individual text columns for each of the 3 tickers
ALTER TABLE ticker_settings
  ADD COLUMN IF NOT EXISTS ticker_1_text TEXT DEFAULT 'USE CODE MANDY ON THRILL.COM – USE CODE MANDY – USE CODE MANDY ON THRILL.COM – USE CODE MANDY',
  ADD COLUMN IF NOT EXISTS ticker_2_text TEXT DEFAULT 'USE CODE MANDY ON THRILL.COM – USE CODE MANDY – USE CODE MANDY ON THRILL.COM – USE CODE MANDY',
  ADD COLUMN IF NOT EXISTS ticker_3_text TEXT DEFAULT 'USE CODE MANDY ON THRILL.COM – USE CODE MANDY – USE CODE MANDY ON THRILL.COM – USE CODE MANDY';
